// ─── iOS → Supabase Broadcast → Plugin ───────────────────────────────────────

/** A voice capture the iOS app has transcribed and wants Claude to process. */
export type CaptureEvent = {
  type: "capture";
  /** UUID generated by iOS before sending; used to correlate ack/speak replies. */
  clientCaptureId: string;
  transcript: string;
  durationSeconds: number;
  /** ISO 8601, e.g. "2026-05-28T14:30:00Z" */
  timestamp: string;
};

// ─── Plugin → Supabase Broadcast → iOS ───────────────────────────────────────

/** Acknowledgement: Claude received and processed the capture. */
export type AckEvent = {
  type: "ack";
  clientCaptureId: string;
};

/** Spoken response: plugin asks iOS to read this text aloud to the user. */
export type SpeakEvent = {
  type: "speak";
  clientCaptureId: string;
  text: string;
};

/** Union of all messages the plugin can send to iOS. */
export type PluginToIosEvent = AckEvent | SpeakEvent;

/** Union of all messages iOS can send to the plugin. */
export type IosToPluginEvent = CaptureEvent;

// ─── Pairing Edge Function ────────────────────────────────────────────────────

/** POST body sent by iOS to /functions/v1/pair */
export type PairRequest = {
  /** 6-char uppercase alphanumeric code displayed by get_pairing_info MCP tool */
  code: string;
};

/** Success response from /functions/v1/pair */
export type PairResponse = {
  channelId: string;
  /** Token for authenticating requests from iOS */
  token: string;
};

// ─── Supabase Broadcast channel names ────────────────────────────────────────

/** Channel on which iOS publishes captures to the plugin. */
export function iosToPluginChannel(channelId: string): string {
  return `relay:${channelId}:ios-to-plugin`;
}

/** Channel on which the plugin publishes replies back to iOS. */
export function pluginToIosChannel(channelId: string): string {
  return `relay:${channelId}:plugin-to-ios`;
}
